//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gw2_AddonHelper.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gw2_AddonHelper.UI.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AboutButtonBackText} ähnelt.
        /// </summary>
        public static string AboutButtonBackText {
            get {
                return ResourceManager.GetString("AboutButtonBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AboutHeaderText} ähnelt.
        /// </summary>
        public static string AboutHeaderText {
            get {
                return ResourceManager.GetString("AboutHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AddonListFilterText} ähnelt.
        /// </summary>
        public static string AddonListFilterText {
            get {
                return ResourceManager.GetString("AddonListFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AddonListGroupAddonPlural} ähnelt.
        /// </summary>
        public static string AddonListGroupAddonPlural {
            get {
                return ResourceManager.GetString("AddonListGroupAddonPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AddonListGroupAddonSingular} ähnelt.
        /// </summary>
        public static string AddonListGroupAddonSingular {
            get {
                return ResourceManager.GetString("AddonListGroupAddonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AddonSourcesEmptyDescription} ähnelt.
        /// </summary>
        public static string AddonSourcesEmptyDescription {
            get {
                return ResourceManager.GetString("AddonSourcesEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AddonSourcesEmptyTitle} ähnelt.
        /// </summary>
        public static string AddonSourcesEmptyTitle {
            get {
                return ResourceManager.GetString("AddonSourcesEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AddonTitleBy} ähnelt.
        /// </summary>
        public static string AddonTitleBy {
            get {
                return ResourceManager.GetString("AddonTitleBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AppUpdateAvailable} ähnelt.
        /// </summary>
        public static string AppUpdateAvailable {
            get {
                return ResourceManager.GetString("AppUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {AppUpdateDownloading} ähnelt.
        /// </summary>
        public static string AppUpdateDownloading {
            get {
                return ResourceManager.GetString("AppUpdateDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {BugreportsNotice} ähnelt.
        /// </summary>
        public static string BugreportsNotice {
            get {
                return ResourceManager.GetString("BugreportsNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonAboutText} ähnelt.
        /// </summary>
        public static string ButtonAboutText {
            get {
                return ResourceManager.GetString("ButtonAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonApplyText} ähnelt.
        /// </summary>
        public static string ButtonApplyText {
            get {
                return ResourceManager.GetString("ButtonApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonAppUpdateText} ähnelt.
        /// </summary>
        public static string ButtonAppUpdateText {
            get {
                return ResourceManager.GetString("ButtonAppUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonCancelText} ähnelt.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonCheckUpdatesText} ähnelt.
        /// </summary>
        public static string ButtonCheckUpdatesText {
            get {
                return ResourceManager.GetString("ButtonCheckUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonDisableAllText} ähnelt.
        /// </summary>
        public static string ButtonDisableAllText {
            get {
                return ResourceManager.GetString("ButtonDisableAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonDisableText} ähnelt.
        /// </summary>
        public static string ButtonDisableText {
            get {
                return ResourceManager.GetString("ButtonDisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonEnableAllText} ähnelt.
        /// </summary>
        public static string ButtonEnableAllText {
            get {
                return ResourceManager.GetString("ButtonEnableAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonEnableText} ähnelt.
        /// </summary>
        public static string ButtonEnableText {
            get {
                return ResourceManager.GetString("ButtonEnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonFindGameExecutableText} ähnelt.
        /// </summary>
        public static string ButtonFindGameExecutableText {
            get {
                return ResourceManager.GetString("ButtonFindGameExecutableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonInstallText} ähnelt.
        /// </summary>
        public static string ButtonInstallText {
            get {
                return ResourceManager.GetString("ButtonInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonOpenText} ähnelt.
        /// </summary>
        public static string ButtonOpenText {
            get {
                return ResourceManager.GetString("ButtonOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonRemoveText} ähnelt.
        /// </summary>
        public static string ButtonRemoveText {
            get {
                return ResourceManager.GetString("ButtonRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonRetryText} ähnelt.
        /// </summary>
        public static string ButtonRetryText {
            get {
                return ResourceManager.GetString("ButtonRetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonSaveText} ähnelt.
        /// </summary>
        public static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonSettingsText} ähnelt.
        /// </summary>
        public static string ButtonSettingsText {
            get {
                return ResourceManager.GetString("ButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonUninstallAllText} ähnelt.
        /// </summary>
        public static string ButtonUninstallAllText {
            get {
                return ResourceManager.GetString("ButtonUninstallAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonUpdatesNoUpdatesText} ähnelt.
        /// </summary>
        public static string ButtonUpdatesNoUpdatesText {
            get {
                return ResourceManager.GetString("ButtonUpdatesNoUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonUpdateText} ähnelt.
        /// </summary>
        public static string ButtonUpdateText {
            get {
                return ResourceManager.GetString("ButtonUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ButtonWelcomeStartText} ähnelt.
        /// </summary>
        public static string ButtonWelcomeStartText {
            get {
                return ResourceManager.GetString("ButtonWelcomeStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ConflictsButtonBackText} ähnelt.
        /// </summary>
        public static string ConflictsButtonBackText {
            get {
                return ResourceManager.GetString("ConflictsButtonBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ConflictsDescriptionText} ähnelt.
        /// </summary>
        public static string ConflictsDescriptionText {
            get {
                return ResourceManager.GetString("ConflictsDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {ConflictsHeaderText} ähnelt.
        /// </summary>
        public static string ConflictsHeaderText {
            get {
                return ResourceManager.GetString("ConflictsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {GameNotFoundError} ähnelt.
        /// </summary>
        public static string GameNotFoundError {
            get {
                return ResourceManager.GetString("GameNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {HeaderSettingsText} ähnelt.
        /// </summary>
        public static string HeaderSettingsText {
            get {
                return ResourceManager.GetString("HeaderSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallAddonError} ähnelt.
        /// </summary>
        public static string InstallAddonError {
            get {
                return ResourceManager.GetString("InstallAddonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerDescriptionAddonDisableText} ähnelt.
        /// </summary>
        public static string InstallerDescriptionAddonDisableText {
            get {
                return ResourceManager.GetString("InstallerDescriptionAddonDisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerDescriptionAddonEnableText} ähnelt.
        /// </summary>
        public static string InstallerDescriptionAddonEnableText {
            get {
                return ResourceManager.GetString("InstallerDescriptionAddonEnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerDescriptionAddonInstallText} ähnelt.
        /// </summary>
        public static string InstallerDescriptionAddonInstallText {
            get {
                return ResourceManager.GetString("InstallerDescriptionAddonInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerDescriptionAddonRemoveText} ähnelt.
        /// </summary>
        public static string InstallerDescriptionAddonRemoveText {
            get {
                return ResourceManager.GetString("InstallerDescriptionAddonRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerDescriptionAddonUpdateText} ähnelt.
        /// </summary>
        public static string InstallerDescriptionAddonUpdateText {
            get {
                return ResourceManager.GetString("InstallerDescriptionAddonUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerHeaderAddonDisableText} ähnelt.
        /// </summary>
        public static string InstallerHeaderAddonDisableText {
            get {
                return ResourceManager.GetString("InstallerHeaderAddonDisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerHeaderAddonEnableText} ähnelt.
        /// </summary>
        public static string InstallerHeaderAddonEnableText {
            get {
                return ResourceManager.GetString("InstallerHeaderAddonEnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerHeaderAddonInstallText} ähnelt.
        /// </summary>
        public static string InstallerHeaderAddonInstallText {
            get {
                return ResourceManager.GetString("InstallerHeaderAddonInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerHeaderAddonRemoveText} ähnelt.
        /// </summary>
        public static string InstallerHeaderAddonRemoveText {
            get {
                return ResourceManager.GetString("InstallerHeaderAddonRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallerHeaderAddonUpdateText} ähnelt.
        /// </summary>
        public static string InstallerHeaderAddonUpdateText {
            get {
                return ResourceManager.GetString("InstallerHeaderAddonUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallProgressCompletedText} ähnelt.
        /// </summary>
        public static string InstallProgressCompletedText {
            get {
                return ResourceManager.GetString("InstallProgressCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallProgressErrorText} ähnelt.
        /// </summary>
        public static string InstallProgressErrorText {
            get {
                return ResourceManager.GetString("InstallProgressErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallProgressInProgressText} ähnelt.
        /// </summary>
        public static string InstallProgressInProgressText {
            get {
                return ResourceManager.GetString("InstallProgressInProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallProgressWaiting} ähnelt.
        /// </summary>
        public static string InstallProgressWaitingText {
            get {
                return ResourceManager.GetString("InstallProgressWaitingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallStateError} ähnelt.
        /// </summary>
        public static string InstallStateError {
            get {
                return ResourceManager.GetString("InstallStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallStateInstalledDisabled} ähnelt.
        /// </summary>
        public static string InstallStateInstalledDisabled {
            get {
                return ResourceManager.GetString("InstallStateInstalledDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallStateInstalledEnabled} ähnelt.
        /// </summary>
        public static string InstallStateInstalledEnabled {
            get {
                return ResourceManager.GetString("InstallStateInstalledEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {InstallStateNotInstalled} ähnelt.
        /// </summary>
        public static string InstallStateNotInstalled {
            get {
                return ResourceManager.GetString("InstallStateNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {LegalNoticeArenanet} ähnelt.
        /// </summary>
        public static string LegalNoticeArenanet {
            get {
                return ResourceManager.GetString("LegalNoticeArenanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {LegalNoticeIcons} ähnelt.
        /// </summary>
        public static string LegalNoticeIcons {
            get {
                return ResourceManager.GetString("LegalNoticeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {Loading} ähnelt.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {OpenAddonError} ähnelt.
        /// </summary>
        public static string OpenAddonError {
            get {
                return ResourceManager.GetString("OpenAddonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {QuickUpdateAvailableText} ähnelt.
        /// </summary>
        public static string QuickUpdateAvailableText {
            get {
                return ResourceManager.GetString("QuickUpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SetGamePathError} ähnelt.
        /// </summary>
        public static string SetGamePathError {
            get {
                return ResourceManager.GetString("SetGamePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SettingsError} ähnelt.
        /// </summary>
        public static string SettingsError {
            get {
                return ResourceManager.GetString("SettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SettingsGamePathDescription} ähnelt.
        /// </summary>
        public static string SettingsGamePathDescription {
            get {
                return ResourceManager.GetString("SettingsGamePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SettingsGamePathText} ähnelt.
        /// </summary>
        public static string SettingsGamePathText {
            get {
                return ResourceManager.GetString("SettingsGamePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SettingsLanguageDescription} ähnelt.
        /// </summary>
        public static string SettingsLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SettingsLanguageText} ähnelt.
        /// </summary>
        public static string SettingsLanguageText {
            get {
                return ResourceManager.GetString("SettingsLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {SettingsThemeText} ähnelt.
        /// </summary>
        public static string SettingsThemeText {
            get {
                return ResourceManager.GetString("SettingsThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {UiErrorWarning} ähnelt.
        /// </summary>
        public static string UiErrorWarning {
            get {
                return ResourceManager.GetString("UiErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {UncategorizedError} ähnelt.
        /// </summary>
        public static string UncategorizedError {
            get {
                return ResourceManager.GetString("UncategorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {UpdateAvailablePaneButtonAppUpdateText} ähnelt.
        /// </summary>
        public static string UpdateAvailablePaneButtonAppUpdateText {
            get {
                return ResourceManager.GetString("UpdateAvailablePaneButtonAppUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {UpdateAvailablePaneButtonSkipText} ähnelt.
        /// </summary>
        public static string UpdateAvailablePaneButtonSkipText {
            get {
                return ResourceManager.GetString("UpdateAvailablePaneButtonSkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {UpdateAvailablePaneNotesHeader} ähnelt.
        /// </summary>
        public static string UpdateAvailablePaneNotesHeader {
            get {
                return ResourceManager.GetString("UpdateAvailablePaneNotesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {UpdateAvailablePaneVersionHeader} ähnelt.
        /// </summary>
        public static string UpdateAvailablePaneVersionHeader {
            get {
                return ResourceManager.GetString("UpdateAvailablePaneVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {WelcomeFindGameExecutableText} ähnelt.
        /// </summary>
        public static string WelcomeFindGameExecutableText {
            get {
                return ResourceManager.GetString("WelcomeFindGameExecutableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {WelcomeSelectLanguageText} ähnelt.
        /// </summary>
        public static string WelcomeSelectLanguageText {
            get {
                return ResourceManager.GetString("WelcomeSelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {WelcomeSettingsHintText} ähnelt.
        /// </summary>
        public static string WelcomeSettingsHintText {
            get {
                return ResourceManager.GetString("WelcomeSettingsHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {WelcomeText} ähnelt.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {WindowTitle} ähnelt.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
